name: terraform plan

description: "The template used for running the packer step in GitHub Actions"

# Were we can define the inputs that our action will accept
inputs:
  CLIENT_ID:
    description: ""
    required: true
  CLIENT_SECRET:
    description: ""
    required: true
  SUBSCRIPTION_ID:
    description: ""
    required: true
  TENANT_ID:
    description: ""
    required: true
  AZURE_CREDENTIALS:
    description: ""
    required: true
  ENV_NAME:
    description: ""
    required: true

runs:
  using: "composite"
  # Defining the action steps(Just one step to be simple)      

  steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with: 
        terraform_version: 1.3.3
      
    # Log into Az cli
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ inputs.AZURE_CREDENTIALS }}

    - name: "Terraform Init"
      run: |
        terraform init -backend-config="../backend_tfvars/${{ inputs.ENV_NAME }}_backend.tfvars"
      shell: bash
      working-directory: "${{ github.workspace }}/src"

    - name: "Terraform Plan"
      run: terraform plan -var-file "../tfvars/${{ inputs.ENV_NAME }}.tfvars"
      shell: bash
      working-directory: "${{ github.workspace }}/src"
