name: 'Terraform - Plan / Apply'

on: 
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches: 
       - main


jobs:
  
  # Run terraform script against dev environment using github environment variables
  terraform-dev-apply:
    name: 'Dev-Apply'

    runs-on: ubuntu-latest
    environment: dev
  
    env:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ENV_NAME: dev

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform
        uses: "./.github/actions/terraform/apply"
        with:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
          ENV_NAME: dev
